Task 2/days of week
vvkar/TMS.Net07.Homework pull request #1
Opened 2021-02-01 08:30 UTC by vvkar

2021-02-02 19:56 UTC, radzevich requested changes

2021-02-02 19:56 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/TMS.Net07.Homework.DaysOfWeek/Program.cs
> +        static void GetDayOfWeekHardLevel(string input)
Keep the empty line between methods

2021-02-02 19:56 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/TMS.Net07.Homework.DaysOfWeek/Program.cs
> +            if ((year + 1) % 400 == 0 || ((year + 1) % 4 == 0 && (year + 1) % 100 != 0))
```suggestion
            check = (year + 1) % 400 == 0 || ((year + 1) % 4 == 0 && (year + 1) % 100 != 0)
```

2021-02-02 19:56 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/TMS.Net07.Homework.DaysOfWeek/Program.cs
> +            if ((year + 1) % 400 == 0 || ((year + 1) % 4 == 0 && (year + 1) % 100 != 0))
Also, please, use `{` `}` brackets, even when there is only one statement inside of `if`, `else` `while` e.t.c.

2021-02-02 19:56 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/TMS.Net07.Homework.DaysOfWeek/Program.cs
> +                }
This `if-else` looks a bit tricky.. It would look better if there were conditions for each month one by one (or switch-case).
The shortest code not always is the most readable code. Remember, that you write code for people, who will read after you

2021-02-02 19:56 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/TMS.Net07.Homework.DaysOfWeek/Program.cs
> +        enum DaysOfWeek
Enum is a `Type`. Types are usually defined on the top of the program

2021-02-02 19:56 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/TMS.Net07.Homework.DaysOfWeek/Program.cs
> +                    return;
Please, use `{`, `}`. If you add one more statement, you may forget to add brackets. This mistake seems to be stupid, bu it's too frequent to don't care about it.

2021-02-02 20:45 UTC, vvkar commented on TMS.Net07.Homework.DaysOfWeek/TMS.Net07.Homework.DaysOfWeek/Program.cs
> +        static void GetDayOfWeekHardLevel(string input)
Got it

2021-02-04 14:49 UTC, radzevich approved these changes

2021-02-06 11:40 UTC, merged