Task 3/convertor calculator
vvkar/TMS.Net07.Homework pull request #2
Opened 2021-02-07 19:09 UTC by vvkar

Решил немного обнаглеть и сделать три разных проекта под три разных уровня. Собсна, по возможности хочу попросить глянуть все три задания.
С последним (сложный калькулятор) произошёл самый большой затык, пришлось потратить много времени и добавить несколько костылей (индексы в массивах в методе "doCalculation", не очень красивый счетчик при присваивании из коллекции в массивы и тд). Исправить можно, но хочу пока на данном этапе получить фидбек.

2021-02-07 20:21 UTC, radzevich requested changes

2021-02-07 20:21 UTC, radzevich commented on TMS.Net07.Homework.ConverterCalculator/TMS.Net07.Homework.ConverterCalculator.Medium/TMS.Net07.Homework.ConverterCalculator.Medium/Program.cs
> +                    Console.WriteLine($"Result: {x / y}");
Have to check that `y` is not `0`

2021-02-07 20:21 UTC, radzevich commented on TMS.Net07.Homework.ConverterCalculator/TMS.Net07.Homework.ConverterCalculator.Medium/TMS.Net07.Homework.ConverterCalculator.Medium/Program.cs
> +                    Console.WriteLine($"Result: {x % y}");
The same here

2021-02-07 20:21 UTC, radzevich commented on TMS.Net07.Homework.ConverterCalculator/TMS.Net07.Homework.ConverterCalculator.Easy/TMS.Net07.Homework.ConverterCalculator/Program.cs
> +            double AmountAfterExchange;
Names should be consistent. Please, use `camelCase` for all variables
```suggestion
            double amountAfterExchange;
```

2021-02-07 20:24 UTC, radzevich commented
В целом, хорошо. Да, есть нюансы по реализации чтения команд пользователя в калькуляторе, но с учётом пройденного материала, это очень даже хороший вариант реализации

2021-02-07 21:13 UTC, vvkar commented on TMS.Net07.Homework.ConverterCalculator/TMS.Net07.Homework.ConverterCalculator.Easy/TMS.Net07.Homework.ConverterCalculator/Program.cs
> +            double AmountAfterExchange;
You mean lowerCamelCase?

2021-02-12 08:35 UTC, radzevich approved these changes

2021-02-12 08:35 UTC, radzevich commented on TMS.Net07.Homework.ConverterCalculator/TMS.Net07.Homework.ConverterCalculator.Easy/TMS.Net07.Homework.ConverterCalculator/Program.cs
> +            double AmountAfterExchange;
Exactly ;)

2021-02-12 13:14 UTC, merged